# Generated by Django 5.1.8 on 2025-04-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_alter_shortenedlink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this link was clicked', verbose_name='Clicked At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the visitor', null=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, help_text='Country of the visitor', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, help_text='City of the visitor', max_length=100, verbose_name='City')),
                ('browser', models.CharField(blank=True, help_text='Browser used by the visitor', max_length=100, verbose_name='Browser')),
                ('device_type', models.CharField(blank=True, help_text='Type of device used (mobile, tablet, desktop)', max_length=50, verbose_name='Device Type')),
                ('operating_system', models.CharField(blank=True, help_text='Operating system of the visitor', max_length=100, verbose_name='Operating System')),
                ('referrer', models.URLField(blank=True, help_text='Website that referred the visitor', max_length=2000, verbose_name='Referrer')),
                ('link', models.ForeignKey(help_text='The shortened link that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.shortenedlink')),
            ],
            options={
                'verbose_name': 'Link Click',
                'verbose_name_plural': 'Link Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['link', 'clicked_at'], name='links_linkc_link_id_49ba9a_idx')],
            },
        ),
    ]
