# Generated by Django 5.1.8 on 2025-05-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_linkclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkclick',
            options={'ordering': ['-clicked_at'], 'permissions': [('view_advanced_statistics', 'Can view advanced statistics')], 'verbose_name': 'Link Click', 'verbose_name_plural': 'Link Clicks'},
        ),
    ]
