# Generated by Django 5.1.8 on 2025-05-10 16:13

import sbily.links.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_alter_linkclick_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='remove_at',
        ),
        migrations.AddField(
            model_name='shortenedlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this shortened link will expire', null=True, validators=[sbily.links.models.future_date_validator], verbose_name='Expires At'),
        ),
    ]
