# Generated by Django 5.1.9 on 2025-05-11 01:30

from django.db import migrations


def populate_destination_urls(apps, schema_editor):
    ShortenedLink = apps.get_model("links", "ShortenedLink")
    for link in ShortenedLink.objects.filter(destination_url__isnull=True):
        link.destination_url = link.original_link
        link.shortened_path = link.shortened_link
        link.save(update_fields=["destination_url", "shortened_path"])

def reverse_population(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_add_destination_url_nullable'),
    ]

    operations = [
        migrations.RunPython(populate_destination_urls, reverse_population),
    ]
