# Generated by Django 5.1.9 on 2025-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_populate_destination_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='original_link',
        ),
        migrations.RemoveField(
            model_name='shortenedlink',
            name='shortened_link',
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='destination_url',
            field=models.URLField(help_text='The destination URL that will be shortened', max_length=2000, verbose_name='Destination URL'),
        ),
    ]
