volumes:
  sbily_local_postgres_data: {}
  sbily_local_postgres_data_backups: {}
  sbily_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sbily_local_django
    container_name: sbily_local_django
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    ports:
      - 8000:8000
    volumes:
      - .:/app:z
    depends_on:
      - postgres
      - redis
      - mailpit
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sbily_production_postgres
    container_name: sbily_local_postgres
    volumes:
      - sbily_local_postgres_data:/var/lib/postgresql/data
      - sbily_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: axllent/mailpit:latest
    container_name: sbily_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:8
    container_name: sbily_local_redis
    volumes:
      - sbily_local_redis_data:/data

  celeryworker:
    <<: *django
    image: sbily_local_celeryworker
    container_name: sbily_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sbily_local_celerybeat
    container_name: sbily_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sbily_local_flower
    container_name: sbily_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: sbily_local_node
    container_name: sbily_local_node
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: pnpm run dev
    ports:
      - "3000:3000"
