volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        DJANGO_AWS_STORAGE_BUCKET_NAME: ${DJANGO_AWS_STORAGE_BUCKET_NAME}
        DJANGO_AWS_S3_CUSTOM_DOMAIN: ${DJANGO_AWS_S3_CUSTOM_DOMAIN}
        STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
    image: sbily_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sbily_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:7
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: sbily_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sbily_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: sbily_production_flower
    command: /start-flower

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: sbily_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
