# Generated by Django 5.1.8 on 2025-04-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_last_four_digits',
            field=models.CharField(blank=True, max_length=4, verbose_name='card last four digits'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe customer ID'),
        ),
    ]
