# Generated by Django 5.1.8 on 2025-04-12 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_last_four_digits',
            field=models.CharField(blank=True, max_length=4, verbose_name='card last four digits'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe customer ID'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='amount')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='status')),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('package', 'Link Package')], max_length=12, verbose_name='payment type')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='transaction ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LinkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=10, verbose_name='link type')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='purchase date')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='unit price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_packages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='users.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'Link package',
                'verbose_name_plural': 'Link packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('incomplete', 'Incomplete')], default='incomplete', max_length=10, verbose_name='status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('is_auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='price')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
