# Generated by Django 5.1.8 on 2025-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_card_last_four_digits_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe subscription ID'),
        ),
    ]
