# Generated by Django 5.1.8 on 2025-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_token_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.RemoveConstraint(
            model_name='token',
            name='unique_user_token_type',
        ),
        migrations.AddField(
            model_name='token',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether this token has been used'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token'], name='users_token_token_b79d33_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['expires_at', 'is_used'], name='users_token_expires_34620d_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('user', 'type'), name='unique_active_user_token_type'),
        ),
    ]
