# Generated by Django 5.1.8 on 2025-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_token_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(db_index=True, help_text='Token expiration date and time'),
        ),
    ]
