# Generated by Django 5.1.8 on 2025-05-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_num_links',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_num_links_temporary',
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_limit_links_used',
            field=models.PositiveIntegerField(default=0, help_text='Monthly limit of links a user has used.', verbose_name='monthly limit links used'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_link_limit',
            field=models.PositiveIntegerField(default=5, help_text='Monthly limit of links a user can create.', verbose_name='monthly link limit'),
        ),
    ]
