# Generated by Django 5.1.9 on 2025-05-12 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_max_num_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_monthly_limit_reset',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the monthly link limit was last reset.', verbose_name='last monthly limit reset'),
        ),
    ]
