# Generated by Django 5.2.7 on 2025-10-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_last_monthly_limit_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('premium', 'Premium'), ('business', 'Business'), ('advanced', 'Advanced')], default='user', help_text='User role', max_length=10, verbose_name='role'),
        ),
    ]
