# Generated by Django 5.2.7 on 2025-10-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_link_limit',
            field=models.PositiveIntegerField(default=10, help_text='Monthly limit of links a user can create.', verbose_name='monthly link limit'),
        ),
    ]
