# Generated by Django 5.2.7 on 2025-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_monthly_link_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_balance',
            field=models.IntegerField(default=0, help_text='Customer balance in cents.', verbose_name='customer balance'),
        ),
    ]
