# Generated by Django 5.2.7 on 2025-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_link_limit',
            field=models.PositiveIntegerField(default='10', help_text='Monthly limit of links a user can create.', verbose_name='monthly link limit'),
        ),
    ]
