# Generated by Django 6.0.4 on 2026-04-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_monthly_link_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_link_limit',
            field=models.PositiveIntegerField(default=10, help_text='Monthly limit of links a user can create.', verbose_name='monthly link limit'),
        ),
    ]
