# Generated by Django 5.1.8 on 2025-05-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='LinkPackage',
        ),
    ]
