# Generated by Django 5.1.9 on 2025-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='price'),
        ),
    ]
