# Generated by Django 5.1.11 on 2025-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='level',
            field=models.CharField(choices=[('premium', 'Premium')], default='premium', max_length=10, verbose_name='level'),
        ),
    ]
