# Generated by Django 5.2.7 on 2025-10-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscription_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='level',
            field=models.CharField(choices=[('premium', 'Premium'), ('business', 'Business'), ('advanced', 'Advanced')], default='premium', max_length=10, verbose_name='level'),
        ),
    ]
