# Generated by Django 5.2.7 on 2025-10-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_subscription_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_schedule_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe subscription schedule ID'),
        ),
    ]
