# Generated by Django 5.2.7 on 2025-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_subscription_stripe_subscription_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.URLField(blank=True, verbose_name='invoice URL'),
        ),
    ]
